package com.bornfire.xbrl.entities.BRBS;
import java.util.List;
public class YourFormDatas {
	private List<BRF201_SUMMARY_ENTITY_A> brf201_SUMMARY_ENTITY_A;
	private List<BRF201_SUMMARY_ENTITY_B> brf201_SUMMARY_ENTITY_B;
	private List<BRF201_SUMMARY_ENTITY_C> brf201_SUMMARY_ENTITY_C;
	private List<BRF201_SUMMARY_ENTITY_D> brf201_SUMMARY_ENTITY_D;
	private List<BRF201_SUMMARY_ENTITY_E> brf201_SUMMARY_ENTITY_E;
	private List<BRF201_SUMMARY_ENTITY_F> brf201_SUMMARY_ENTITY_F;
	private List<BRF201_SUMMARY_ENTITY_G> brf201_SUMMARY_ENTITY_G;
	public List<BRF201_SUMMARY_ENTITY_A> getBrf201_SUMMARY_ENTITY_A() {
		return brf201_SUMMARY_ENTITY_A;
	}
	public void setBrf201_SUMMARY_ENTITY_A(List<BRF201_SUMMARY_ENTITY_A> brf201_SUMMARY_ENTITY_A) {
		this.brf201_SUMMARY_ENTITY_A = brf201_SUMMARY_ENTITY_A;
	}
	public List<BRF201_SUMMARY_ENTITY_B> getBrf201_SUMMARY_ENTITY_B() {
		return brf201_SUMMARY_ENTITY_B;
	}
	public void setBrf201_SUMMARY_ENTITY_B(List<BRF201_SUMMARY_ENTITY_B> brf201_SUMMARY_ENTITY_B) {
		this.brf201_SUMMARY_ENTITY_B = brf201_SUMMARY_ENTITY_B;
	}
	public List<BRF201_SUMMARY_ENTITY_C> getBrf201_SUMMARY_ENTITY_C() {
		return brf201_SUMMARY_ENTITY_C;
	}
	public void setBrf201_SUMMARY_ENTITY_C(List<BRF201_SUMMARY_ENTITY_C> brf201_SUMMARY_ENTITY_C) {
		this.brf201_SUMMARY_ENTITY_C = brf201_SUMMARY_ENTITY_C;
	}
	public List<BRF201_SUMMARY_ENTITY_D> getBrf201_SUMMARY_ENTITY_D() {
		return brf201_SUMMARY_ENTITY_D;
	}
	public void setBrf201_SUMMARY_ENTITY_D(List<BRF201_SUMMARY_ENTITY_D> brf201_SUMMARY_ENTITY_D) {
		this.brf201_SUMMARY_ENTITY_D = brf201_SUMMARY_ENTITY_D;
	}
	public List<BRF201_SUMMARY_ENTITY_E> getBrf201_SUMMARY_ENTITY_E() {
		return brf201_SUMMARY_ENTITY_E;
	}
	public void setBrf201_SUMMARY_ENTITY_E(List<BRF201_SUMMARY_ENTITY_E> brf201_SUMMARY_ENTITY_E) {
		this.brf201_SUMMARY_ENTITY_E = brf201_SUMMARY_ENTITY_E;
	}
	public List<BRF201_SUMMARY_ENTITY_F> getBrf201_SUMMARY_ENTITY_F() {
		return brf201_SUMMARY_ENTITY_F;
	}
	public void setBrf201_SUMMARY_ENTITY_F(List<BRF201_SUMMARY_ENTITY_F> brf201_SUMMARY_ENTITY_F) {
		this.brf201_SUMMARY_ENTITY_F = brf201_SUMMARY_ENTITY_F;
	}
	public List<BRF201_SUMMARY_ENTITY_G> getBrf201_SUMMARY_ENTITY_G() {
		return brf201_SUMMARY_ENTITY_G;
	}
	public void setBrf201_SUMMARY_ENTITY_G(List<BRF201_SUMMARY_ENTITY_G> brf201_SUMMARY_ENTITY_G) {
		this.brf201_SUMMARY_ENTITY_G = brf201_SUMMARY_ENTITY_G;
	}
}
